version: '3.0'
services:
  api:
    build:
      context: .
      dockerfile: dockerfile-amd64
    ports:
      - "5000:5000"
      - "5678:5678"
    environment:
      - SLACK_API_TOKEN=
      - MONGO_CONNECTION_STRING=
      - READ_SLACK_CHANNEL_ID=
      - WRITE_SLACK_CHANNEL_ID=
      - SLACK_VERIFICATION_TOKEN=
    depends_on:
      - mongo
    command: 'python3 -m debugpy --listen 0.0.0.0:5678 -m flask --app main run --host=0.0.0.0'
  mongo:
    image: mongo
    ports:
      - "27017:27017"