version: '3.0'
services:
  api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - SLACK_API_TOKEN=xoxb-241070135347-1373084066946-RKPQf2uO6s7Oi0F8InCgwgkx
      - MONGO_CONNECTION_STRING=mongodb://mongo:27017
      - READ_SLACK_CHANNEL_ID=C0692LSN85R
      - WRITE_SLACK_CHANNEL_ID=G01ASA2SG22
      - SLACK_VERIFICATION_TOKEN=u99mYutBGu9ckh4JnOk8YU3P
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"