version: '3.0'
services:
  api:
    build: .
    ports:
      - "5555:5000"
    environment:
      - SLACK_API_TOKEN=value
      - MONGO_CONNECTION_STRING=mongodb://mongo:27017
      - SLACK_CHANNEL_ID=G01ASA2SG22
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"